pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo "This is build stage"
            }
        }
        stage('Test') {
            steps {
                echo "This is Test stage"
            }
        }
        stage('store') { 
            steps {
                echo "This is store stage" 
            }
        }
        stage('modify') { 
            steps {
                echo "This is modify stage"
            }
        }
        
        stage('new-entry') { 
            steps {
                echo "This is modify stage"
            }
        } 
        stage('double-copy') { 
            steps {
                echo "This is modify stage"
            }
        }
        
    }
}